// Code generated by hertz generator.

package checkout

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/suutest/app/frontend/middleware"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.Auth()} // 在根路径上应用中间件，使得这些中间件会自动应用到所有子路由（例如/checkout/result,/checkout/waiting都会继承这个中间件）
}

func _checkoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkout0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutresultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutwaitingMw() []app.HandlerFunc {
	// your code...
	return nil
}
