// Code generated by Kitex v0.9.1. DO NOT EDIT.

package stockservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	stock "github.com/suutest/rpc_gen/kitex_gen/stock"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	BatchGetStocks(ctx context.Context, Req *stock.GetStocksReq, callOptions ...callopt.Option) (r *stock.GetStocksResp, err error)
	DeductStocks(ctx context.Context, Req *stock.DeductStocksReq, callOptions ...callopt.Option) (r *stock.DeductStocksResp, err error)
	OccupyStocks(ctx context.Context, Req *stock.OccupyStocksReq, callOptions ...callopt.Option) (r *stock.OccupyStocksResp, err error)
	RecoverStocks(ctx context.Context, Req *stock.RecoverStocksReq, callOptions ...callopt.Option) (r *stock.RecoverStocksResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kStockServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kStockServiceClient struct {
	*kClient
}

func (p *kStockServiceClient) BatchGetStocks(ctx context.Context, Req *stock.GetStocksReq, callOptions ...callopt.Option) (r *stock.GetStocksResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetStocks(ctx, Req)
}

func (p *kStockServiceClient) DeductStocks(ctx context.Context, Req *stock.DeductStocksReq, callOptions ...callopt.Option) (r *stock.DeductStocksResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeductStocks(ctx, Req)
}

func (p *kStockServiceClient) OccupyStocks(ctx context.Context, Req *stock.OccupyStocksReq, callOptions ...callopt.Option) (r *stock.OccupyStocksResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.OccupyStocks(ctx, Req)
}

func (p *kStockServiceClient) RecoverStocks(ctx context.Context, Req *stock.RecoverStocksReq, callOptions ...callopt.Option) (r *stock.RecoverStocksResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RecoverStocks(ctx, Req)
}
